### ISSUE TITLE
Transfer money bewteen players

### ISSUE THREAD

**Issue by LBIRE** [ACROSS-Lab/BacHungHai-Waste#9]
Add a phase to the game. 
At the end of each round, the remaining money of each player is put in the center if there is enough to conduct an action. The players have two minutes to discuss about how this money could be used, and by what player. 

Is it possible ?

**Comment by LBIRE** [comment]
At the end of each turn, the unused money is transferred to a pot at the center of the game and the players have 1 minute to decide how the commune (represented by the animator) will use it. The commune can pick one action with this money and the action is unchanged in its scale (impact on one village only)

**Comment by LBIRE** [comment]
Bug cagnotte : working well for turn 1 and then for turn 2 and after, lends a huge amount of money for unknown reason instead of the good amount of remaining money (example : 300 tokens given at the end of turn 2, 600 tokens given at the end of turn 3)

**Comment by ptaillandier** [comment]
I pushed a fix, could you test?

**Comment by LBIRE** [comment]
Not fixed : now when the cagnotte is given to a player, the player gets the cagnotte + the base budget he had at the begining of the turn
